/*****************************************************************
 *
 *  This file automatically generated - DO NOT EDIT!
 *
 *****************************************************************/

#ifndef EPILOGUE_INSTALL_H
#define EPILOGUE_INSTALL_H

#define INSTALL_ON_LITTLE_ENDIAN 1
#define INSTALL_ON_BIG_ENDIAN 0
#define INSTALL_OEM_LAYOUT_GLUE_MACROS 0
#define INSTALL_TYPECHECKING_LAYOUT_GLUE_MACROS 0
#define INSTALL_UNALIGNED_BIGENDIAN_LAYOUT_GLUE_MACROS 0
#define INSTALL_on_msdos 0
#define INSTALL_on_microsoft 1
#define INSTALL_on_winsock 1
#define INSTALL_on_msvc40 1
#define INSTALL_on_win32 1
#define INSTALL_COMMON 1
#define INSTALL_COMMON_MD5 0
#define INSTALL_COMMON_PRNG 0
#define INSTALL_ENVOY 1
#define INSTALL_ENVOY_SNMP_GROUP_V1 1
#define INSTALL_ENVOY_SNMP_GROUP_V2 1
#define INSTALL_ENVOY_SNMP_VERSION_1 1
#define INSTALL_ENVOY_SNMP_VERSION_2 1
#define INSTALL_ENVOY_USE_MIBCOMPILER 1
#define INSTALL_ENVOY_MAIN_AGENT 1
#define INSTALL_ENVOY_SNMP_RFC1445_VIEWS 0
#define INSTALL_ENVOY_TWO_CHAR_MACROS 0
#define INSTALL_ENVOY_SNMP_PROXY 0
#define INSTALL_ENVOY_EPI_SUBAGENT_SCHEME 0
#define INSTALL_ENVOY_EPI_MASTER 0
#define INSTALL_ENVOY_EPI_SUB 0
#define INSTALL_ENVOY_AGENTX 0
#define INSTALL_ENVOY_AGENTX_MASTER 0
#define INSTALL_ENVOY_AGENTX_SUB 0
#define INSTALL_ENVOY_AGENTX_INDEX 1
#define INSTALL_ENVOY_AGENTX_NEXT_CHECK 1
#define INSTALL_ENVOY_SNMP_LOCK 0
#define INSTALL_ENVOY_CONTINUE_REENTRANT 0
#define INSTALL_ENVOY_SNMP_SERIALIZE 0
#define INSTALL_ENVOY_40_VB_FREE_COMPAT 0
#define INSTALL_ENVOY_SNMP_USE_V2_TYPES 0
#define INSTALL_ENVOY_SNMP_VERSION_USEC 0
#define INSTALL_ENVOY_TEST 0
#define INSTALL_ATTACHE 0
#define INSTALL_ATTACHE_MIB 0
#define INSTALL_EMISSARY 1
#define INSTALL_EMISSARY_LOADTREE_ENUM 1
#define INSTALL_EMISSARY_NAMETREE_ENUM 1
#define INSTALL_EMISSARY_EMULATE_STRTOUL 1
#define INSTALL_EMISSARY_ARENA_ALLOCATION 1
#define INSTALL_EMISSARY_CONFLICTS_ARE_FATAL 0
#define INSTALL_EMISSARY_DEBUG 0
#define INSTALL_EMISSARY_READTREE_INDX 0
#define INSTALL_EMISSARY_FAST_SCANNER 0
#define INSTALL_EMISSARY_BACKSLASH 0
#define INSTALL_EMISSARY_EMULATE_STRCMPI 0
#define INSTALL_EMISSARY_EMULATE_STRNCMPI 0
#define INSTALL_EMISSARY_EMULATE_STRTOL 0
#define INSTALL_EMISSARY_TEST_ALL 0
#define INSTALL_EMISSARY_ARRAY 0
#define INSTALL_EMISSARY_LISP 0
#define INSTALL_EMISSARY_LOADTREE 0
#define INSTALL_EMISSARY_MANAGER 0
#define INSTALL_EMISSARY_NAMETREE 0
#define INSTALL_EMISSARY_NUMBERS 1
#define INSTALL_EMISSARY_PARTIAL 1
#define INSTALL_EMISSARY_SKELETON 1
#define INSTALL_EMISSARY_STUB 1
#define INSTALL_EMISSARY_TRAP 1
#define INSTALL_EMISSARY_DECORUM 0
#define INSTALL_EMISSARY_DECORUM_AGENTURL 1

#endif /* EPILOGUE_INSTALL_H */
