// SnmpTextCon.h: interfaces for the SNMPv2 Textual Convention entities.
//
//////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////////////
// The Hyperon Library
// Copyright (c) 2004-2005 by Library Dream Team (Oli Tsisaruk, Serge Gaziev)
// Permission to use, copy, modify, distribute and sell this software for any 
//     purpose is hereby granted without fee, provided that the above copyright 
//     notice appear in all copies and that both that copyright notice and this 
//     permission notice appear in supporting documentation.
// Authors make no representations about the suitability of this software for 
//     any purpose. It is provided "as is" without express or implied warranty.
////////////////////////////////////////////////////////////////////////////////

#ifndef SNMP_SNMPTEXTCON_INC_
#define SNMP_SNMPTEXTCON_INC_

#include "SnmpTypes.h"

namespace snmpfwk
{

//////////////////////////////////////////////////
// class DateAndTime
//
//! A date-time specification
/*!
	SYNTAX OCTET STRING ( SIZE ( 8 | 11) )
	Note that if only local time is known, then timezone 
	information (fields 8-10) is not present.
*/
class DateAndTime
{
public:
	enum { maxSize = 11 };

public:
	DateAndTime();

	const SnmpAsnOctets toOctets() const;
	const pstring toString() const;

	/*
	  fromString(const pstring& str)
	  fills the DateAndTime values from a given string.
	  Input string should be earlier generated by toString method or have correct format:
	  "<year>-<month>-<day>,<hours>:<minutes>:<seconds>.<deciseconds>, <direction><utcHours>:<utcMinutes>"
	*/
	bool fromString(const pstring& str);

	// TODO: Expand methods if needed
	static const DateAndTime now();

private:
	u16 _year; // 0..65536
	u8 _month; // 1..12
	u8 _day; // 1..31 
	u8 _hour; // 0..23 
	u8 _minutes; // 0..59 
	u8 _seconds; // 0..60 (use 60 for leap-second)
	u8 _deciseconds; // 0..9
	// timezone information
	char _direction; // '+' / '-'
	u8 _utcHours; // 0..11
	u8 _utcMinutes; // 0..59
};

} // namespace snmpfwk

#endif // SNMP_SNMPTEXTCON_INC_
