# Makefile - gkEpilog.dsw

.PHONY: all
all: \
	gkEpilog

.PHONY: gkEpilog
gkEpilog:
	$(MAKE) -f gkEpilog.mak

.PHONY: clean
clean:
	$(MAKE) -f gkEpilog.mak clean

.PHONY: depends
depends:
	$(MAKE) -f gkEpilog.mak depends

